data_set = {
    "celebrities": [
        {"name": "Taylor Swift", "followers_count": 270_000_000,
         "description": "Singer-songwriter known for her narrative songwriting and evolution across multiple genres.",
         "country": "USA"},
        {"name": "Cristiano Ronaldo", "followers_count": 600_000_000,
         "description": "Professional footballer, widely considered one of the greatest in history.",
         "country": "Portugal"},
        {"name": "Selena Gomez", "followers_count": 430_000_000,
         "description": "Singer and actress known for her roles in Disney shows and successful music career.",
         "country": "USA"},
        {"name": "Dwayne Johnson", "followers_count": 350_000_000,
         "description": "Actor and former WWE wrestler, popularly known as 'The Rock'.", "country": "USA"},
        {"name": "Kylie Jenner", "followers_count": 400_000_000,
         "description": "Reality TV star and entrepreneur, known for her makeup line, Kylie Cosmetics.",
         "country": "USA"},
        {"name": "Ariana Grande", "followers_count": 390_000_000,
         "description": "Pop singer and actress known for her wide vocal range and hit songs.", "country": "USA"},
        {"name": "Lionel Messi", "followers_count": 490_000_000,
         "description": "Argentinian professional footballer, recognized as one of the best in the world.",
         "country": "Argentina"},
        {"name": "Kim Kardashian", "followers_count": 360_000_000,
         "description": "Reality TV star, businesswoman, and cultural icon.", "country": "USA"},
        {"name": "Beyoncé", "followers_count": 260_000_000,
         "description": "Singer, songwriter, actress, and producer known for her influence in pop music.",
         "country": "USA"},
        {"name": "Justin Bieber", "followers_count": 290_000_000,
         "description": "Pop singer and songwriter with a huge following since his teenage years.",
         "country": "Canada"},
        # Additional entries up to 50...
    ],

    "teams": [
        {"name": "Manchester United", "followers_count": 60_000_000,
         "description": "English professional football club based in Manchester.", "country": "UK"},
        {"name": "Golden State Warriors", "followers_count": 30_000_000,
         "description": "American professional basketball team based in San Francisco.", "country": "USA"},
        {"name": "Los Angeles Lakers", "followers_count": 40_000_000,
         "description": "Professional basketball team with a storied history in the NBA.", "country": "USA"},
        {"name": "FC Barcelona", "followers_count": 110_000_000,
         "description": "Spanish professional football club known for its global following and legacy.",
         "country": "Spain"},
        {"name": "Real Madrid", "followers_count": 120_000_000,
         "description": "One of the most successful and popular football clubs in the world.", "country": "Spain"},
        {"name": "New York Yankees", "followers_count": 5_000_000,
         "description": "American professional baseball team based in the Bronx, New York.", "country": "USA"},
        {"name": "Paris Saint-Germain", "followers_count": 60_000_000,
         "description": "French professional football club known for its star-studded lineup.", "country": "France"},
        {"name": "Chicago Bulls", "followers_count": 20_000_000,
         "description": "NBA team popularized globally during the Michael Jordan era.", "country": "USA"},
        {"name": "Juventus", "followers_count": 50_000_000,
         "description": "Italian professional football club based in Turin.", "country": "Italy"},
        {"name": "Dallas Cowboys", "followers_count": 5_000_000,
         "description": "Professional American football team known as 'America's Team'.", "country": "USA"},
        # Additional entries up to 50...
    ],

    "items": [
        {"name": "iPhone", "followers_count": 27_000_000,
         "description": "Flagship smartphone by Apple known for its sleek design and iOS system.", "country": "USA"},
        {"name": "Nike Shoes", "followers_count": 140_000_000,
         "description": "Popular sportswear and footwear brand with global influence.", "country": "USA"},
        {"name": "Gucci", "followers_count": 50_000_000,
         "description": "Italian luxury brand known for fashion, leather goods, and accessories.", "country": "Italy"},
        {"name": "Adidas", "followers_count": 40_000_000,
         "description": "German multinational known for athletic wear and sneakers.", "country": "Germany"},
        {"name": "Coca-Cola", "followers_count": 3_000_000,
         "description": "Global beverage brand known for its iconic cola drink.", "country": "USA"},
        {"name": "Samsung Galaxy", "followers_count": 20_000_000,
         "description": "Popular smartphone line by Samsung, a leading Android device.", "country": "South Korea"},
        {"name": "Rolex", "followers_count": 15_000_000,
         "description": "Luxury watch brand known for its iconic designs and high craftsmanship.",
         "country": "Switzerland"},
        {"name": "Louis Vuitton", "followers_count": 45_000_000,
         "description": "Luxury fashion brand known for its high-end bags and apparel.", "country": "France"},
        {"name": "Sony PlayStation", "followers_count": 25_000_000,
         "description": "Popular gaming console brand with a massive following.", "country": "Japan"},
        {"name": "Mercedes-Benz", "followers_count": 30_000_000,
         "description": "German luxury automobile manufacturer known for its high-quality vehicles.",
         "country": "Germany"},
        # Additional entries up to 50...
    ],

    # Additional categories could be added as needed...
}
